### ISSUE TITLE
The current Windows binaries are the debug version

### ISSUE THREAD

**Issue by gd4c** [Benni3D/cmdcalc#1]
Requiring VCRUNTIME140**D**.dll
Can you release non-debug ones, please? 🙂

**Comment by realchonk** [comment]
I've rewritten this program like 6 hours ago to incorparate libreadline for a better command-line experience.
I'm gonna try to compile it with MinGW since I switched to Linux.

**Comment by gd4c** [comment]
Very cool. Thanks!

Downloaded and tested quickly and it seems to be working fine!

I'd ask you to consider linking the libraries statically. A single binary is always better to handle as a user and the size increase shouldn't matter.

**Comment by realchonk** [comment]
I tried but there seems to be a bug in the toolchain or the libraries.
I might try it in the future.
